






"use client";

import { Card, Row, Col, Typography, Empty, Tag } from "antd";
import { 
  BulbOutlined, 
  InfoCircleOutlined, 
  ThunderboltOutlined 
} from "@ant-design/icons";

const { Text, Title, Paragraph } = Typography;

export default function AssistantCards({ latestMeeting = null }) {
  // Safe parsing logic
  const summaryData = typeof latestMeeting?.ai_summary === 'string' 
    ? JSON.parse(latestMeeting.ai_summary) 
    : latestMeeting?.ai_summary;

  const overview = summaryData?.data?.overview || "No overview available for the latest meeting.";
  const keyPoints = summaryData?.data?.key_points || [];

  return (
    <div style={{ padding: "0 24px", marginTop: 20 }}>
      <Title level={4} style={{ marginBottom: 20 }}>
        <ThunderboltOutlined style={{ marginRight: 8, color: '#1890ff' }} />
        Personal Assistant: Latest Insights
      </Title>

      <Row gutter={[20, 20]}>
        {/* Card 1: AI Overview */}
        <Col xs={24} lg={16}>
          <Card 
            title={<span><InfoCircleOutlined /> Meeting Overview</span>}
            style={{ borderRadius: 12, height: '100%', border: "1px solid #f0f0f0" }}
          >
            {latestMeeting ? (
              <>
                <Paragraph style={{ fontSize: '16px', lineHeight: '1.6', color: '#444' }}>
                  {overview}
                </Paragraph>
                <Text type="secondary" style={{ fontSize: '12px' }}>
                  Generated by {latestMeeting.model || "AI Model"} • 
                  {new Date(latestMeeting.created_at).toLocaleDateString()}
                </Text>
              </>
            ) : (
              <Empty description="No meeting data found" />
            )}
          </Card>
        </Col>

        {/* Card 2: Key Discussion Points */}
        <Col xs={24} lg={8}>
          <Card 
            title={<span><BulbOutlined /> Key Points</span>}
            style={{ borderRadius: 12, height: '100%', border: "1px solid #f0f0f0" }}
          >
            {keyPoints.length > 0 ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {keyPoints.map((point, index) => (
                  <Tag 
                    key={index} 
                    color="blue" 
                    style={{ 
                      padding: '5px 10px', 
                      borderRadius: '6px', 
                      whiteSpace: 'normal', 
                      height: 'auto',
                      fontSize: '14px'
                    }}
                  >
                    • {point}
                  </Tag>
                ))}
              </div>
            ) : (
              <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="No key points identified" />
            )}
          </Card>
        </Col>
      </Row>
    </div>
  );
}











// "use client";

// import { Card, Row, Col, Typography, Space, Flex } from "antd";
// import {
//   PlusOutlined,
//   WifiOutlined,
//   MessageOutlined,
//   CheckOutlined,
// } from "@ant-design/icons";

// const { Text } = Typography;

// const cardStyle = {
//   borderRadius: 10,
//   padding: 10,
//   minHeight: 120,
//   // Changed background color to a light off-white/gray
//   backgroundColor: '#fcfcfc',
//   // Using a very subtle border for definition
//   border: "1px solid #eeeeee", 
//   cursor: "pointer",
//   transition: "all 0.3s",
//   bodyStyle: { padding: 10 },
// };

// export default function AssistantCards() {
//   return (
//     <div style={{ padding: 30 }}>

//       <Flex justify="space-between" align="center" style={{ marginBottom: 20 }}>
//         <Space align="center" size={8}>
//           <Text style={{ fontSize: 16, color: '#404040' }}>
//             ✢ Personal Assistant
//           </Text>
//         </Space>
//         <Space size={4}>
//           <Text style={{ color: '#4A90E2', cursor: 'pointer', fontSize: 14 }}>
//             Manage
//           </Text>
//           <Text style={{ color: '#b0b0b0', fontSize: 14 }}>
//             ⓘ
//           </Text>
//         </Space>
//       </Flex>

//       <Row gutter={20}>

//         <Col span={8}>
//           <Card
//             style={cardStyle}
//             hoverable
//           >
//             <Space orientation="vertical" size={10} style={{ width: '100%' }}>

//               <div
//                 style={{
//                   background: "#988aff",
//                   padding: 8,
//                   borderRadius: 6,
//                   width: 38,
//                   height: 38,
//                   display: 'flex',
//                   alignItems: 'center',
//                   justifyContent: 'center',
//                 }}
//               >
//                 <WifiOutlined
//                   style={{
//                     color: "#ffffff",
//                     fontSize: 22,
//                   }}
//                 />
//               </div>

//               <Space orientation="vertical" size={2}>
//                 <Space size={4}>
//                   <Text strong style={{ fontSize: 16 }}>
//                     Daily Digest
//                   </Text>
//                   <CheckOutlined style={{ color: '#52c41a', fontSize: 12 }} />
//                 </Space>
//                 <Text type="secondary" style={{ fontSize: 14 }}>
//                   No digest yet
//                 </Text>
//               </Space>

//             </Space>
//           </Card>
//         </Col>


//         <Col span={8}>
//           <Card
//             style={cardStyle}
//             hoverable
//           >
//             <Space orientation="vertical" size={10} style={{ width: '100%' }}>

//               <div
//                 style={{
//                   background: "#c1f06b",
//                   padding: 8,
//                   borderRadius: 6,
//                   width: 38,
//                   height: 38,
//                   display: 'flex',
//                   alignItems: 'center',
//                   justifyContent: 'center',
//                 }}
//               >
//                 <MessageOutlined
//                   style={{
//                     color: "#404040",
//                     fontSize: 22,
//                   }}
//                 />
//               </div>

//               <Space orientation="vertical" size={2}>
//                 <Text strong style={{ fontSize: 16 }}>
//                   Popular Topics
//                 </Text>
//                 <Text type="secondary" style={{ fontSize: 14 }}>
//                   No topics yet
//                 </Text>
//               </Space>

//             </Space>
//           </Card>
//         </Col>


//         <Col span={8}>
//           <Card
//             style={cardStyle}
//             hoverable
//           >
//             <Space orientation="vertical" size={10} style={{ width: '100%' }}>

//               <div
//                 style={{
//                   background: 'transparent',
//                   padding: 8,
//                   borderRadius: 6,
//                   width: 38,
//                   height: 38,
//                   display: 'flex',
//                   alignItems: 'center',
//                   justifyContent: 'center',
//                 }}
//               >
//                 <PlusOutlined
//                   style={{
//                     color: "#b0b0b0",
//                     fontSize: 22,
//                   }}
//                 />
//               </div>

//               <Space orientation="vertical" size={2}>
//                 <Text strong style={{ fontSize: 16 }}>
//                   Add Skills
//                 </Text>
//                 <Text type="secondary" style={{ fontSize: 14 }}>
//                   Browse 100+
//                 </Text>
//               </Space>

//             </Space>
//           </Card>
//         </Col>
//       </Row>
//     </div>
//   );
// }