import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import { Suspense } from "react";
import UserSchemaHandler from "@/components/UserSchemaHandler";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js Dashboard",
  description: "Generated by Next.js App Router",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}><StackProvider app={stackClientApp}><StackTheme>
        <StackProvider app={stackClientApp}>
          <StackTheme>
          <Suspense fallback={null}> 
              <UserSchemaHandler />
            </Suspense>
            {children}
          </StackTheme>
        </StackProvider>
      </StackTheme></StackProvider></body>
    </html>
  );
}
