import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import HelpButton from "@/components/Ui/HelpButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js Dashboard",
  description: "Generated by Next.js App Router",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        {/* <HelpButton/> */}
      </body>
    </html>
  );
}
